/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */


export interface paths {
  "/api/classes/": {
    /**
     * Returns a list of all available classes in the db. 
     * @description Returns a list of all available classes in the db. If authenticated, also returns the classes created by the user.
     */
    get: {
      parameters: {
        header?: {
          authorization?: string;
        };
      };
      responses: {
        /** @description Default Response */
        200: {
          content: {
            "application/json": components["schemas"]["classSchemas"]["getClassListResponseSchema"];
          };
        };
      };
    };
  };
  "/api/classes/random": {
    /**
     * Returns the details of a random class in the database. 
     * @description Returns the details of a random class from list of classes available to the user in the database.
     */
    get: {
      parameters: {
        header?: {
          authorization?: string;
        };
      };
      responses: {
        /** @description Default Response */
        200: {
          content: {
            "application/json": components["schemas"]["classSchemas"]["getClassResponseSchema"];
          };
        };
      };
    };
  };
  "/api/classes/withvariants": {
    /**
     * Returns a list of all available combinations of classes and variants in the db. 
     * @description Returns a list of all available combinations of classes and variants in the db. If authenticated, also returns the classes created by the user.
     */
    get: {
      parameters: {
        header?: {
          authorization?: string;
        };
      };
      responses: {
        /** @description Default Response */
        200: {
          content: {
            "application/json": components["schemas"]["classSchemas"]["getClassWithVariantsListResponseSchema"];
          };
        };
      };
    };
  };
  "/api/classes/{classId}": {
    /**
     * Returns the details of the class corresponding to the given id. 
     * @description Returns the details of the class corresponding to the given id.
     */
    get: {
      parameters: {
        header?: {
          authorization?: string;
        };
      };
      responses: {
        /** @description Default Response */
        200: {
          content: {
            "application/json": components["schemas"]["classSchemas"]["getClassResponseSchema"];
          };
        };
      };
    };
  };
  "/api/npcs/": {
    /**
     * Creates a new random npc using the settings provided. 
     * @description Creates a new random npc using the settings provided.
     */
    post: {
      parameters: {
        header?: {
          authorization?: string;
        };
      };
      requestBody?: {
        content: {
          "application/json": components["schemas"]["npcSchemas"]["createRandomNpcInputSchema"];
        };
      };
      responses: {
        /** @description Default Response */
        200: {
          content: {
            "application/json": components["schemas"]["npcSchemas"]["createRandomNpcResponseSchema"];
          };
        };
      };
    };
  };
  "/api/npcs/four": {
    /**
     * [MS ONLY] Creates four new random npcs using the settings provided. 
     * @description Creates four new random npcs using the settings provided. Only accessible through monstershuffler.com
     */
    post: {
      parameters: {
        header?: {
          authorization?: string;
        };
      };
      requestBody?: {
        content: {
          "application/json": components["schemas"]["npcSchemas"]["createRandomNpcInputSchema"];
        };
      };
      responses: {
        /** @description Default Response */
        200: {
          content: {
            "application/json": components["schemas"]["npcSchemas"]["createFourRandomNpcsResponseSchema"];
          };
        };
      };
    };
  };
  "/api/professions/": {
    /**
     * Returns a list of all available professions in the db. 
     * @description Returns a list of all available professions in the db. If authenticated, also returns the list of professions created by the user.
     */
    get: {
      parameters: {
        header?: {
          authorization?: string;
        };
      };
      responses: {
        /** @description Default Response */
        200: {
          content: {
            "application/json": components["schemas"]["professionSchemas"]["getProfessionListResponseSchema"];
          };
        };
      };
    };
  };
  "/api/professions/{professionId}": {
    /**
     * Returns the details of the profession corresponding to the given id. 
     * @description Returns the details of the profession corresponding to the given id.
     */
    get: {
      parameters: {
        header?: {
          authorization?: string;
        };
      };
      responses: {
        /** @description Default Response */
        200: {
          content: {
            "application/json": components["schemas"]["professionSchemas"]["getProfessionResponseSchema"];
          };
        };
      };
    };
  };
  "/api/professions/random": {
    /**
     * Returns the details of a random profession from the database. 
     * @description Returns the details of a random profession from list of professions available to the user in the database.
     */
    get: {
      parameters: {
        header?: {
          authorization?: string;
        };
      };
      responses: {
        /** @description Default Response */
        200: {
          content: {
            "application/json": components["schemas"]["professionSchemas"]["getProfessionResponseSchema"];
          };
        };
      };
    };
  };
  "/api/races/": {
    /**
     * Returns a list of all available races in the db. 
     * @description Returns a list of all available races in the db. If authenticated, also returns the races created by the user.
     */
    get: {
      parameters: {
        header?: {
          authorization?: string;
        };
      };
      responses: {
        /** @description Default Response */
        200: {
          content: {
            "application/json": components["schemas"]["raceSchemas"]["getRaceListResponseSchema"];
          };
        };
      };
    };
  };
  "/api/races/withvariants": {
    /**
     * Returns a list of all available combinations of races and variants in the db. 
     * @description Returns a list of all available combinations of races and variants in the db. If authenticated, also returns the races created by the user.
     */
    get: {
      parameters: {
        header?: {
          authorization?: string;
        };
      };
      responses: {
        /** @description Default Response */
        200: {
          content: {
            "application/json": components["schemas"]["raceSchemas"]["getRaceWithVariantsListResponseSchema"];
          };
        };
      };
    };
  };
  "/api/races/{raceId}": {
    /**
     * Returns the details of the race corresponding to the given id. 
     * @description Returns the details of the race corresponding to the given id.
     */
    get: {
      parameters: {
        header?: {
          authorization?: string;
        };
      };
      responses: {
        /** @description Default Response */
        200: {
          content: {
            "application/json": components["schemas"]["raceSchemas"]["getRaceResponseSchema"];
          };
        };
      };
    };
  };
  "/api/races/random": {
    /**
     * Returns the details of a random race from the database. 
     * @description Returns the details of a random race from list of races available to the user in the database.
     */
    get: {
      parameters: {
        header?: {
          authorization?: string;
        };
      };
      responses: {
        /** @description Default Response */
        200: {
          content: {
            "application/json": components["schemas"]["raceSchemas"]["getRaceResponseSchema"];
          };
        };
      };
    };
  };
  "/api/users/login": {
    /**
     * Logs in a user and returns an access token. 
     * @description Logs in a user and returns an access token. Logged users can then receive their creations through other routes, and access other protected routes.
     */
    post: {
      requestBody?: {
        content: {
          "application/json": components["schemas"]["userSchemas"]["loginSchema"];
        };
      };
      responses: {
        /** @description Default Response */
        200: {
          content: {
            "application/json": components["schemas"]["userSchemas"]["loginResponseSchema"];
          };
        };
      };
    };
  };
  "/api/users/": {
    /**
     * [MS ONLY] Registers a new user in the database. 
     * @description Registers a new user in the database. Only accessible through monstershuffler.com
     */
    post: {
      requestBody?: {
        content: {
          "application/json": components["schemas"]["userSchemas"]["createUserSchema"];
        };
      };
      responses: {
        /** @description Default Response */
        201: {
          content: {
            "application/json": components["schemas"]["userSchemas"]["createUserResponseSchema"];
          };
        };
      };
    };
  };
  "/api/users/verify": {
    /**
     * [MS ONLY] Verifies the user's email and activates the account. 
     * @description Activates an account by providing the validation token sent via email. Only accessible through monstershuffler.com
     */
    put: {
      requestBody?: {
        content: {
          "application/json": components["schemas"]["userSchemas"]["activateUserSchema"];
        };
      };
      responses: {
        /** @description Default Response */
        200: {
          content: {
            "application/json": components["schemas"]["userSchemas"]["loginResponseSchema"];
          };
        };
      };
    };
  };
  "/api/users/reactivation": {
    /**
     * [MS ONLY] Resends the activation email to the user. 
     * @description Resends the activation email to the user. The user will have to reset their password as well. Only accessible through monstershuffler.com
     */
    post: {
      requestBody?: {
        content: {
          "application/json": components["schemas"]["userSchemas"]["reactivateUserSchema"];
        };
      };
      responses: {
        /** @description Default Response */
        200: {
          content: {
            "application/json": string;
          };
        };
        /** @description Default Response */
        404: {
          content: {
            "application/json": string;
          };
        };
      };
    };
  };
  "/api/users/pwdreset": {
    /**
     * [MS ONLY] Resets the user's password. 
     * @description Resets the user's password. Only accessible through monstershuffler.com
     */
    put: {
      requestBody?: {
        content: {
          "application/json": components["schemas"]["userSchemas"]["resetPasswordSchema"];
        };
      };
      responses: {
        /** @description Default Response */
        200: {
          content: {
            "application/json": components["schemas"]["userSchemas"]["loginResponseSchema"];
          };
        };
        /** @description Default Response */
        404: {
          content: {
            "application/json": string;
          };
        };
      };
    };
  };
  "/api/users/me": {
    /**
     * [MS ONLY] Returns the details of the user corresponding to the given token. 
     * @description Returns the details of the user corresponding to the given token. Only accessible through monstershuffler.com
     */
    get: {
      parameters: {
        header: {
          authorization: string;
        };
      };
      responses: {
        /** @description Default Response */
        200: {
          content: {
            "application/json": components["schemas"]["userSchemas"]["getUserResponseSchema"];
          };
        };
      };
    };
  };
  "/api/converter/converter": {
    /**
     * Converts objects from the old monstershuffler format to the new one. 
     * @description Converts objects from the old monstershuffler format to the new one.
     */
    get: {
      parameters: {
        header: {
          authorization: string;
        };
      };
      responses: {
      };
    };
  };
}

export type webhooks = Record<string, never>;

export interface components {
  schemas: {
    classSchemas: {
      updateClassSchema: {
        object: {
          name: string;
          armor?: ({
            AC: string;
            name: string;
            cost?: string;
            /** @enum {string} */
            type?: "light" | "medium" | "heavy";
            maxDex?: string;
            minStr?: string;
            weight?: string;
            /** @enum {string} */
            stealthDis?: "0" | "1";
          }) | ({
            choice: {
              /** @enum {string} */
              type: "random";
              number?: number;
              /** @enum {string} */
              resultType: "object" | "nameId";
              /** @enum {string} */
              source: "objects" | "languages" | "skills";
              objectType?: number;
              filters?: ({
                  keyName: string;
                  keyValues: (string)[];
                })[];
              chosenAlready?: ({
                  id?: number;
                  value: string;
                  levelMin?: string;
                })[];
            };
          });
          subtypes?: (components["schemas"]["classSchemas"]["updateClassSchema"]["object"]["armor"]["anyOf"]["1"]["choice"]["chosenAlready"]["items"])[];
          speeds?: {
            base?: string;
            burrow?: string;
            climb?: string;
            fly?: string;
            hover?: string;
            swim?: string;
          };
          savingThrows?: (components["schemas"]["classSchemas"]["updateClassSchema"]["object"]["armor"]["anyOf"]["1"]["choice"]["chosenAlready"]["items"])[];
          skills?: (components["schemas"]["classSchemas"]["updateClassSchema"]["object"]["armor"]["anyOf"]["1"]["choice"]["chosenAlready"]["items"])[] | components["schemas"]["classSchemas"]["updateClassSchema"]["object"]["armor"]["anyOf"]["1"] | {
            choice: {
              /** @enum {string} */
              type: "list";
              number: number;
              list: (components["schemas"]["classSchemas"]["updateClassSchema"]["object"]["armor"]["anyOf"]["1"]["choice"]["chosenAlready"]["items"])[];
              isRepeatable?: boolean;
            };
          };
          resistances?: (components["schemas"]["classSchemas"]["updateClassSchema"]["object"]["armor"]["anyOf"]["1"]["choice"]["chosenAlready"]["items"])[];
          immunities?: (components["schemas"]["classSchemas"]["updateClassSchema"]["object"]["armor"]["anyOf"]["1"]["choice"]["chosenAlready"]["items"])[];
          vulnerabilities?: (components["schemas"]["classSchemas"]["updateClassSchema"]["object"]["armor"]["anyOf"]["1"]["choice"]["chosenAlready"]["items"])[];
          conditionImmunities?: (components["schemas"]["classSchemas"]["updateClassSchema"]["object"]["armor"]["anyOf"]["1"]["choice"]["chosenAlready"]["items"])[];
          senses?: {
            blindsight?: string;
            darkvision?: string;
            tremorsense?: string;
            truesight?: string;
          };
          isBlind?: boolean;
          canSpeak?: boolean;
          telepathy?: string;
          languages?: (components["schemas"]["classSchemas"]["updateClassSchema"]["object"]["armor"]["anyOf"]["1"]["choice"]["chosenAlready"]["items"])[] | components["schemas"]["classSchemas"]["updateClassSchema"]["object"]["armor"]["anyOf"]["1"] | components["schemas"]["classSchemas"]["updateClassSchema"]["object"]["skills"]["anyOf"]["2"];
          actions?: ({
              tag: string;
              /** @enum {string} */
              actionType?: "trait" | "legendary" | "action" | "reaction" | "bonus" | "attack" | "multiattack" | "mythic" | "lair";
              subType?: string;
              source?: string;
              tags?: (string)[];
              priority?: number;
              variants: (({
                  name: string;
                  description: string;
                  /** @enum {string} */
                  type: "trait" | "legendary" | "action" | "reaction" | "bonus" | "attack" | "multiattack" | "mythic" | "lair";
                  levelMin?: number;
                  levelMax?: number;
                  /** @enum {string} */
                  ability?: "STR" | "DEX" | "CON" | "INT" | "WIS" | "CHA";
                  charges?: string;
                  recharge?: string;
                  cost?: string;
                  values?: ({
                      name: string;
                      type?: string;
                      expression: string;
                    } | {
                      name: string;
                      type?: string;
                      expression?: string;
                      dice: {
                        die: string;
                        diceNumber: string;
                        diceIncrement: string;
                        levelMin: string;
                        levelMax: string;
                        levelInterval: string;
                      };
                    } | {
                      name: string;
                      type?: string;
                      incrProgression: {
                        levelInterval: string;
                        levelIncrement: string;
                        levelMin: string;
                        base: string;
                        increment: string;
                      };
                    })[];
                  attacks?: ({
                      name: string;
                      replaceName?: boolean;
                      attributes: {
                        reach?: string;
                        targets?: string;
                        name?: string;
                        cost?: string;
                        weight?: string;
                        damageType?: string;
                        special?: string;
                        die?: string;
                        diceNumber?: string;
                        dieV?: string;
                        diceNumberV?: string;
                        range?: string;
                        rangeMax?: string;
                        properties: (string)[];
                      } | components["schemas"]["classSchemas"]["updateClassSchema"]["object"]["armor"]["anyOf"]["1"];
                      enchantment?: {
                        type: string;
                        dice?: components["schemas"]["classSchemas"]["updateClassSchema"]["object"]["actions"]["items"]["variants"]["items"]["anyOf"]["0"]["values"]["items"]["anyOf"]["1"]["dice"];
                        expression?: string;
                      };
                    })[];
                }) | components["schemas"]["classSchemas"]["updateClassSchema"]["object"]["armor"]["anyOf"]["1"] | components["schemas"]["classSchemas"]["updateClassSchema"]["object"]["skills"]["anyOf"]["2"])[];
            })[];
          bonuses?: {
            HPBonus?: {
              name?: string;
              value: string;
            };
            ACBonus?: components["schemas"]["classSchemas"]["updateClassSchema"]["object"]["bonuses"]["HPBonus"];
            sizeBonus?: components["schemas"]["classSchemas"]["updateClassSchema"]["object"]["bonuses"]["HPBonus"];
            speedBaseBonus?: components["schemas"]["classSchemas"]["updateClassSchema"]["object"]["bonuses"]["HPBonus"];
            speedBurrowBonus?: components["schemas"]["classSchemas"]["updateClassSchema"]["object"]["bonuses"]["HPBonus"];
            speedClimbBonus?: components["schemas"]["classSchemas"]["updateClassSchema"]["object"]["bonuses"]["HPBonus"];
            speedFlyBonus?: components["schemas"]["classSchemas"]["updateClassSchema"]["object"]["bonuses"]["HPBonus"];
            speedHoverBonus?: components["schemas"]["classSchemas"]["updateClassSchema"]["object"]["bonuses"]["HPBonus"];
            speedSwimBonus?: components["schemas"]["classSchemas"]["updateClassSchema"]["object"]["bonuses"]["HPBonus"];
            STRBonus?: components["schemas"]["classSchemas"]["updateClassSchema"]["object"]["bonuses"]["HPBonus"];
            DEXBonus?: components["schemas"]["classSchemas"]["updateClassSchema"]["object"]["bonuses"]["HPBonus"];
            CONBonus?: components["schemas"]["classSchemas"]["updateClassSchema"]["object"]["bonuses"]["HPBonus"];
            INTBonus?: components["schemas"]["classSchemas"]["updateClassSchema"]["object"]["bonuses"]["HPBonus"];
            WISBonus?: components["schemas"]["classSchemas"]["updateClassSchema"]["object"]["bonuses"]["HPBonus"];
            CHABonus?: components["schemas"]["classSchemas"]["updateClassSchema"]["object"]["bonuses"]["HPBonus"];
            STRSaveBonus?: components["schemas"]["classSchemas"]["updateClassSchema"]["object"]["bonuses"]["HPBonus"];
            DEXSaveBonus?: components["schemas"]["classSchemas"]["updateClassSchema"]["object"]["bonuses"]["HPBonus"];
            CONSaveBonus?: components["schemas"]["classSchemas"]["updateClassSchema"]["object"]["bonuses"]["HPBonus"];
            INTSaveBonus?: components["schemas"]["classSchemas"]["updateClassSchema"]["object"]["bonuses"]["HPBonus"];
            WISSaveBonus?: components["schemas"]["classSchemas"]["updateClassSchema"]["object"]["bonuses"]["HPBonus"];
            CHASaveBonus?: components["schemas"]["classSchemas"]["updateClassSchema"]["object"]["bonuses"]["HPBonus"];
            AthleticsBonus?: components["schemas"]["classSchemas"]["updateClassSchema"]["object"]["bonuses"]["HPBonus"];
            AcrobaticsBonus?: components["schemas"]["classSchemas"]["updateClassSchema"]["object"]["bonuses"]["HPBonus"];
            SleightOfHandBonus?: components["schemas"]["classSchemas"]["updateClassSchema"]["object"]["bonuses"]["HPBonus"];
            StealthBonus?: components["schemas"]["classSchemas"]["updateClassSchema"]["object"]["bonuses"]["HPBonus"];
            ArcanaBonus?: components["schemas"]["classSchemas"]["updateClassSchema"]["object"]["bonuses"]["HPBonus"];
            HistoryBonus?: components["schemas"]["classSchemas"]["updateClassSchema"]["object"]["bonuses"]["HPBonus"];
            InvestigationBonus?: components["schemas"]["classSchemas"]["updateClassSchema"]["object"]["bonuses"]["HPBonus"];
            NatureBonus?: components["schemas"]["classSchemas"]["updateClassSchema"]["object"]["bonuses"]["HPBonus"];
            ReligionBonus?: components["schemas"]["classSchemas"]["updateClassSchema"]["object"]["bonuses"]["HPBonus"];
            AnimalHandlingBonus?: components["schemas"]["classSchemas"]["updateClassSchema"]["object"]["bonuses"]["HPBonus"];
            InsightBonus?: components["schemas"]["classSchemas"]["updateClassSchema"]["object"]["bonuses"]["HPBonus"];
            MedicineBonus?: components["schemas"]["classSchemas"]["updateClassSchema"]["object"]["bonuses"]["HPBonus"];
            PerceptionBonus?: components["schemas"]["classSchemas"]["updateClassSchema"]["object"]["bonuses"]["HPBonus"];
            SurvivalBonus?: components["schemas"]["classSchemas"]["updateClassSchema"]["object"]["bonuses"]["HPBonus"];
            DeceptionBonus?: components["schemas"]["classSchemas"]["updateClassSchema"]["object"]["bonuses"]["HPBonus"];
            IntimidationBonus?: components["schemas"]["classSchemas"]["updateClassSchema"]["object"]["bonuses"]["HPBonus"];
            PerformanceBonus?: components["schemas"]["classSchemas"]["updateClassSchema"]["object"]["bonuses"]["HPBonus"];
            PersuasionBonus?: components["schemas"]["classSchemas"]["updateClassSchema"]["object"]["bonuses"]["HPBonus"];
            blindsightBonus?: components["schemas"]["classSchemas"]["updateClassSchema"]["object"]["bonuses"]["HPBonus"];
            darkvisionBonus?: components["schemas"]["classSchemas"]["updateClassSchema"]["object"]["bonuses"]["HPBonus"];
            tremorsenseBonus?: components["schemas"]["classSchemas"]["updateClassSchema"]["object"]["bonuses"]["HPBonus"];
            truesightBonus?: components["schemas"]["classSchemas"]["updateClassSchema"]["object"]["bonuses"]["HPBonus"];
            rangedAttackBonus?: components["schemas"]["classSchemas"]["updateClassSchema"]["object"]["bonuses"]["HPBonus"];
            rangedDamageBonus?: components["schemas"]["classSchemas"]["updateClassSchema"]["object"]["bonuses"]["HPBonus"];
            meleeAttackBonus?: components["schemas"]["classSchemas"]["updateClassSchema"]["object"]["bonuses"]["HPBonus"];
            meleeDamageBonus?: components["schemas"]["classSchemas"]["updateClassSchema"]["object"]["bonuses"]["HPBonus"];
            spellAttackBonus?: components["schemas"]["classSchemas"]["updateClassSchema"]["object"]["bonuses"]["HPBonus"];
            spellDamageBonus?: components["schemas"]["classSchemas"]["updateClassSchema"]["object"]["bonuses"]["HPBonus"];
            weaponAttackBonus?: components["schemas"]["classSchemas"]["updateClassSchema"]["object"]["bonuses"]["HPBonus"];
            weaponDamageBonus?: components["schemas"]["classSchemas"]["updateClassSchema"]["object"]["bonuses"]["HPBonus"];
          };
          spells?: {
            hasSlots?: boolean;
            ability?: components["schemas"]["classSchemas"]["updateClassSchema"]["object"]["actions"]["items"]["variants"]["items"]["anyOf"]["0"]["ability"];
            groups?: ({
                tag: string;
                levelMin?: string;
                timesDay?: string;
                timesDayMax?: string;
                spells: (components["schemas"]["classSchemas"]["updateClassSchema"]["object"]["armor"]["anyOf"]["1"]["choice"]["chosenAlready"]["items"])[] | components["schemas"]["classSchemas"]["updateClassSchema"]["object"]["armor"]["anyOf"]["1"] | components["schemas"]["classSchemas"]["updateClassSchema"]["object"]["skills"]["anyOf"]["2"];
              })[];
          };
          enableGenerator?: boolean;
          image?: {
            imgdir: string;
            lastedited: number;
          };
          searchTags?: (string)[];
          environments?: (string)[];
          backgroundImage?: string;
          background?: {
            [key: string]: unknown;
          };
        };
        game: number;
      };
      createClassSchema: {
        game: components["schemas"]["classSchemas"]["updateClassSchema"]["game"];
        object: components["schemas"]["classSchemas"]["updateClassSchema"]["object"];
      };
      getClassWithVariantsListResponseSchema: {
        list: ({
            id: number;
            userid: number;
            name: string;
            other_objects: ({
                id: components["schemas"]["classSchemas"]["getClassWithVariantsListResponseSchema"]["list"]["items"]["id"];
                name: components["schemas"]["classSchemas"]["getClassWithVariantsListResponseSchema"]["list"]["items"]["name"];
                userid: components["schemas"]["classSchemas"]["getClassWithVariantsListResponseSchema"]["list"]["items"]["userid"];
              })[];
          })[];
      };
      getClassListResponseSchema: {
        list: ({
            id: components["schemas"]["classSchemas"]["getClassWithVariantsListResponseSchema"]["list"]["items"]["id"];
            userid: components["schemas"]["classSchemas"]["getClassWithVariantsListResponseSchema"]["list"]["items"]["userid"];
            name: components["schemas"]["classSchemas"]["getClassWithVariantsListResponseSchema"]["list"]["items"]["name"];
          })[];
      };
      getClassResponseSchema: {
        object: components["schemas"]["classSchemas"]["updateClassSchema"]["object"];
        id: components["schemas"]["classSchemas"]["getClassWithVariantsListResponseSchema"]["list"]["items"]["id"];
      };
    };
    npcSchemas: {
      createRandomNpcInputSchema: {
        /** @enum {string} */
        levelType?: "random" | "randomPeasantsMostly";
        /** @enum {string} */
        classType?: "specificClass" | "randomClass" | "randomClassProfession" | "randomProfessionMostly" | "randomProfession" | "specificProfession";
        classId?: number;
        classvariantId?: components["schemas"]["npcSchemas"]["createRandomNpcInputSchema"]["classId"];
        professionId?: components["schemas"]["npcSchemas"]["createRandomNpcInputSchema"]["classId"];
        primaryRaceId?: components["schemas"]["npcSchemas"]["createRandomNpcInputSchema"]["classId"];
        secondaryRaceId?: components["schemas"]["npcSchemas"]["createRandomNpcInputSchema"]["classId"];
        primaryRacevariantId?: components["schemas"]["npcSchemas"]["createRandomNpcInputSchema"]["classId"];
        secondaryRacevariantId?: components["schemas"]["npcSchemas"]["createRandomNpcInputSchema"]["classId"];
        primaryRacePercentage?: number;
        secondaryRacePercentage?: number;
      };
      createRandomNpcResponseSchema: {
        npc: {
          character: {
            name: string;
            prename?: string;
            surname?: string;
            generic?: boolean;
            /** @enum {string} */
            pronouns?: "male" | "female" | "neutral" | "thing";
            race?: {
              name: string;
              /** @enum {string} */
              pronouns?: "male" | "female" | "neutral" | "thing";
              size?: string;
              type?: string;
              isSwarm?: boolean;
              swarmSize?: string;
              subtypes?: ({
                  id?: number;
                  value: string;
                  levelMin?: string;
                })[];
              alignment?: [number,number,number];
              armor?: ({
                AC: string;
                name: string;
                cost?: string;
                /** @enum {string} */
                type?: "light" | "medium" | "heavy";
                maxDex?: string;
                minStr?: string;
                weight?: string;
                /** @enum {string} */
                stealthDis?: "0" | "1";
              }) | ({
                choice: {
                  /** @enum {string} */
                  type: "random";
                  number?: number;
                  /** @enum {string} */
                  resultType: "object" | "nameId";
                  /** @enum {string} */
                  source: "objects" | "languages" | "skills";
                  objectType?: number;
                  filters?: ({
                      keyName: string;
                      keyValues: (string)[];
                    })[];
                  chosenAlready?: (components["schemas"]["npcSchemas"]["createRandomNpcResponseSchema"]["npc"]["character"]["race"]["subtypes"]["items"])[];
                };
              });
              HD?: number;
              abilitiesLimit?: string;
              speeds?: {
                base?: string;
                burrow?: string;
                climb?: string;
                fly?: string;
                hover?: string;
                swim?: string;
              };
              savingThrows?: (components["schemas"]["npcSchemas"]["createRandomNpcResponseSchema"]["npc"]["character"]["race"]["subtypes"]["items"])[];
              skills?: (components["schemas"]["npcSchemas"]["createRandomNpcResponseSchema"]["npc"]["character"]["race"]["subtypes"]["items"])[] | components["schemas"]["npcSchemas"]["createRandomNpcResponseSchema"]["npc"]["character"]["race"]["armor"]["anyOf"]["1"] | {
                choice: {
                  /** @enum {string} */
                  type: "list";
                  number: number;
                  list: (components["schemas"]["npcSchemas"]["createRandomNpcResponseSchema"]["npc"]["character"]["race"]["subtypes"]["items"])[];
                  isRepeatable?: boolean;
                };
              };
              resistances?: (components["schemas"]["npcSchemas"]["createRandomNpcResponseSchema"]["npc"]["character"]["race"]["subtypes"]["items"])[];
              immunities?: (components["schemas"]["npcSchemas"]["createRandomNpcResponseSchema"]["npc"]["character"]["race"]["subtypes"]["items"])[];
              vulnerabilities?: (components["schemas"]["npcSchemas"]["createRandomNpcResponseSchema"]["npc"]["character"]["race"]["subtypes"]["items"])[];
              conditionImmunities?: (components["schemas"]["npcSchemas"]["createRandomNpcResponseSchema"]["npc"]["character"]["race"]["subtypes"]["items"])[];
              senses?: {
                blindsight?: string;
                darkvision?: string;
                tremorsense?: string;
                truesight?: string;
              };
              isBlind?: boolean;
              canSpeak?: boolean;
              telepathy?: string;
              languages?: (components["schemas"]["npcSchemas"]["createRandomNpcResponseSchema"]["npc"]["character"]["race"]["subtypes"]["items"])[] | components["schemas"]["npcSchemas"]["createRandomNpcResponseSchema"]["npc"]["character"]["race"]["armor"]["anyOf"]["1"] | components["schemas"]["npcSchemas"]["createRandomNpcResponseSchema"]["npc"]["character"]["race"]["skills"]["anyOf"]["2"];
              actions?: ({
                  tag: string;
                  /** @enum {string} */
                  actionType?: "trait" | "legendary" | "action" | "reaction" | "bonus" | "attack" | "multiattack" | "mythic" | "lair";
                  subType?: string;
                  source?: string;
                  tags?: (string)[];
                  priority?: number;
                  variants: (({
                      name: string;
                      description: string;
                      /** @enum {string} */
                      type: "trait" | "legendary" | "action" | "reaction" | "bonus" | "attack" | "multiattack" | "mythic" | "lair";
                      levelMin?: number;
                      levelMax?: number;
                      /** @enum {string} */
                      ability?: "STR" | "DEX" | "CON" | "INT" | "WIS" | "CHA";
                      charges?: string;
                      recharge?: string;
                      cost?: string;
                      values?: ({
                          name: string;
                          type?: string;
                          expression: string;
                        } | {
                          name: string;
                          type?: string;
                          expression?: string;
                          dice: {
                            die: string;
                            diceNumber: string;
                            diceIncrement: string;
                            levelMin: string;
                            levelMax: string;
                            levelInterval: string;
                          };
                        } | {
                          name: string;
                          type?: string;
                          incrProgression: {
                            levelInterval: string;
                            levelIncrement: string;
                            levelMin: string;
                            base: string;
                            increment: string;
                          };
                        })[];
                      attacks?: ({
                          name: string;
                          replaceName?: boolean;
                          attributes: {
                            reach?: string;
                            targets?: string;
                            name?: string;
                            cost?: string;
                            weight?: string;
                            damageType?: string;
                            special?: string;
                            die?: string;
                            diceNumber?: string;
                            dieV?: string;
                            diceNumberV?: string;
                            range?: string;
                            rangeMax?: string;
                            properties: (string)[];
                          } | components["schemas"]["npcSchemas"]["createRandomNpcResponseSchema"]["npc"]["character"]["race"]["armor"]["anyOf"]["1"];
                          enchantment?: {
                            type: string;
                            dice?: components["schemas"]["npcSchemas"]["createRandomNpcResponseSchema"]["npc"]["character"]["race"]["actions"]["items"]["variants"]["items"]["anyOf"]["0"]["values"]["items"]["anyOf"]["1"]["dice"];
                            expression?: string;
                          };
                        })[];
                    }) | components["schemas"]["npcSchemas"]["createRandomNpcResponseSchema"]["npc"]["character"]["race"]["armor"]["anyOf"]["1"] | components["schemas"]["npcSchemas"]["createRandomNpcResponseSchema"]["npc"]["character"]["race"]["skills"]["anyOf"]["2"])[];
                })[];
              bonuses?: {
                HPBonus?: {
                  name?: string;
                  value: string;
                };
                ACBonus?: components["schemas"]["npcSchemas"]["createRandomNpcResponseSchema"]["npc"]["character"]["race"]["bonuses"]["HPBonus"];
                sizeBonus?: components["schemas"]["npcSchemas"]["createRandomNpcResponseSchema"]["npc"]["character"]["race"]["bonuses"]["HPBonus"];
                speedBaseBonus?: components["schemas"]["npcSchemas"]["createRandomNpcResponseSchema"]["npc"]["character"]["race"]["bonuses"]["HPBonus"];
                speedBurrowBonus?: components["schemas"]["npcSchemas"]["createRandomNpcResponseSchema"]["npc"]["character"]["race"]["bonuses"]["HPBonus"];
                speedClimbBonus?: components["schemas"]["npcSchemas"]["createRandomNpcResponseSchema"]["npc"]["character"]["race"]["bonuses"]["HPBonus"];
                speedFlyBonus?: components["schemas"]["npcSchemas"]["createRandomNpcResponseSchema"]["npc"]["character"]["race"]["bonuses"]["HPBonus"];
                speedHoverBonus?: components["schemas"]["npcSchemas"]["createRandomNpcResponseSchema"]["npc"]["character"]["race"]["bonuses"]["HPBonus"];
                speedSwimBonus?: components["schemas"]["npcSchemas"]["createRandomNpcResponseSchema"]["npc"]["character"]["race"]["bonuses"]["HPBonus"];
                STRBonus?: components["schemas"]["npcSchemas"]["createRandomNpcResponseSchema"]["npc"]["character"]["race"]["bonuses"]["HPBonus"];
                DEXBonus?: components["schemas"]["npcSchemas"]["createRandomNpcResponseSchema"]["npc"]["character"]["race"]["bonuses"]["HPBonus"];
                CONBonus?: components["schemas"]["npcSchemas"]["createRandomNpcResponseSchema"]["npc"]["character"]["race"]["bonuses"]["HPBonus"];
                INTBonus?: components["schemas"]["npcSchemas"]["createRandomNpcResponseSchema"]["npc"]["character"]["race"]["bonuses"]["HPBonus"];
                WISBonus?: components["schemas"]["npcSchemas"]["createRandomNpcResponseSchema"]["npc"]["character"]["race"]["bonuses"]["HPBonus"];
                CHABonus?: components["schemas"]["npcSchemas"]["createRandomNpcResponseSchema"]["npc"]["character"]["race"]["bonuses"]["HPBonus"];
                STRSaveBonus?: components["schemas"]["npcSchemas"]["createRandomNpcResponseSchema"]["npc"]["character"]["race"]["bonuses"]["HPBonus"];
                DEXSaveBonus?: components["schemas"]["npcSchemas"]["createRandomNpcResponseSchema"]["npc"]["character"]["race"]["bonuses"]["HPBonus"];
                CONSaveBonus?: components["schemas"]["npcSchemas"]["createRandomNpcResponseSchema"]["npc"]["character"]["race"]["bonuses"]["HPBonus"];
                INTSaveBonus?: components["schemas"]["npcSchemas"]["createRandomNpcResponseSchema"]["npc"]["character"]["race"]["bonuses"]["HPBonus"];
                WISSaveBonus?: components["schemas"]["npcSchemas"]["createRandomNpcResponseSchema"]["npc"]["character"]["race"]["bonuses"]["HPBonus"];
                CHASaveBonus?: components["schemas"]["npcSchemas"]["createRandomNpcResponseSchema"]["npc"]["character"]["race"]["bonuses"]["HPBonus"];
                AthleticsBonus?: components["schemas"]["npcSchemas"]["createRandomNpcResponseSchema"]["npc"]["character"]["race"]["bonuses"]["HPBonus"];
                AcrobaticsBonus?: components["schemas"]["npcSchemas"]["createRandomNpcResponseSchema"]["npc"]["character"]["race"]["bonuses"]["HPBonus"];
                SleightOfHandBonus?: components["schemas"]["npcSchemas"]["createRandomNpcResponseSchema"]["npc"]["character"]["race"]["bonuses"]["HPBonus"];
                StealthBonus?: components["schemas"]["npcSchemas"]["createRandomNpcResponseSchema"]["npc"]["character"]["race"]["bonuses"]["HPBonus"];
                ArcanaBonus?: components["schemas"]["npcSchemas"]["createRandomNpcResponseSchema"]["npc"]["character"]["race"]["bonuses"]["HPBonus"];
                HistoryBonus?: components["schemas"]["npcSchemas"]["createRandomNpcResponseSchema"]["npc"]["character"]["race"]["bonuses"]["HPBonus"];
                InvestigationBonus?: components["schemas"]["npcSchemas"]["createRandomNpcResponseSchema"]["npc"]["character"]["race"]["bonuses"]["HPBonus"];
                NatureBonus?: components["schemas"]["npcSchemas"]["createRandomNpcResponseSchema"]["npc"]["character"]["race"]["bonuses"]["HPBonus"];
                ReligionBonus?: components["schemas"]["npcSchemas"]["createRandomNpcResponseSchema"]["npc"]["character"]["race"]["bonuses"]["HPBonus"];
                AnimalHandlingBonus?: components["schemas"]["npcSchemas"]["createRandomNpcResponseSchema"]["npc"]["character"]["race"]["bonuses"]["HPBonus"];
                InsightBonus?: components["schemas"]["npcSchemas"]["createRandomNpcResponseSchema"]["npc"]["character"]["race"]["bonuses"]["HPBonus"];
                MedicineBonus?: components["schemas"]["npcSchemas"]["createRandomNpcResponseSchema"]["npc"]["character"]["race"]["bonuses"]["HPBonus"];
                PerceptionBonus?: components["schemas"]["npcSchemas"]["createRandomNpcResponseSchema"]["npc"]["character"]["race"]["bonuses"]["HPBonus"];
                SurvivalBonus?: components["schemas"]["npcSchemas"]["createRandomNpcResponseSchema"]["npc"]["character"]["race"]["bonuses"]["HPBonus"];
                DeceptionBonus?: components["schemas"]["npcSchemas"]["createRandomNpcResponseSchema"]["npc"]["character"]["race"]["bonuses"]["HPBonus"];
                IntimidationBonus?: components["schemas"]["npcSchemas"]["createRandomNpcResponseSchema"]["npc"]["character"]["race"]["bonuses"]["HPBonus"];
                PerformanceBonus?: components["schemas"]["npcSchemas"]["createRandomNpcResponseSchema"]["npc"]["character"]["race"]["bonuses"]["HPBonus"];
                PersuasionBonus?: components["schemas"]["npcSchemas"]["createRandomNpcResponseSchema"]["npc"]["character"]["race"]["bonuses"]["HPBonus"];
                blindsightBonus?: components["schemas"]["npcSchemas"]["createRandomNpcResponseSchema"]["npc"]["character"]["race"]["bonuses"]["HPBonus"];
                darkvisionBonus?: components["schemas"]["npcSchemas"]["createRandomNpcResponseSchema"]["npc"]["character"]["race"]["bonuses"]["HPBonus"];
                tremorsenseBonus?: components["schemas"]["npcSchemas"]["createRandomNpcResponseSchema"]["npc"]["character"]["race"]["bonuses"]["HPBonus"];
                truesightBonus?: components["schemas"]["npcSchemas"]["createRandomNpcResponseSchema"]["npc"]["character"]["race"]["bonuses"]["HPBonus"];
                rangedAttackBonus?: components["schemas"]["npcSchemas"]["createRandomNpcResponseSchema"]["npc"]["character"]["race"]["bonuses"]["HPBonus"];
                rangedDamageBonus?: components["schemas"]["npcSchemas"]["createRandomNpcResponseSchema"]["npc"]["character"]["race"]["bonuses"]["HPBonus"];
                meleeAttackBonus?: components["schemas"]["npcSchemas"]["createRandomNpcResponseSchema"]["npc"]["character"]["race"]["bonuses"]["HPBonus"];
                meleeDamageBonus?: components["schemas"]["npcSchemas"]["createRandomNpcResponseSchema"]["npc"]["character"]["race"]["bonuses"]["HPBonus"];
                spellAttackBonus?: components["schemas"]["npcSchemas"]["createRandomNpcResponseSchema"]["npc"]["character"]["race"]["bonuses"]["HPBonus"];
                spellDamageBonus?: components["schemas"]["npcSchemas"]["createRandomNpcResponseSchema"]["npc"]["character"]["race"]["bonuses"]["HPBonus"];
                weaponAttackBonus?: components["schemas"]["npcSchemas"]["createRandomNpcResponseSchema"]["npc"]["character"]["race"]["bonuses"]["HPBonus"];
                weaponDamageBonus?: components["schemas"]["npcSchemas"]["createRandomNpcResponseSchema"]["npc"]["character"]["race"]["bonuses"]["HPBonus"];
              };
              spells?: {
                hasSlots?: boolean;
                ability?: components["schemas"]["npcSchemas"]["createRandomNpcResponseSchema"]["npc"]["character"]["race"]["actions"]["items"]["variants"]["items"]["anyOf"]["0"]["ability"];
                groups?: ({
                    tag: string;
                    levelMin?: string;
                    timesDay?: string;
                    timesDayMax?: string;
                    spells: (components["schemas"]["npcSchemas"]["createRandomNpcResponseSchema"]["npc"]["character"]["race"]["subtypes"]["items"])[] | components["schemas"]["npcSchemas"]["createRandomNpcResponseSchema"]["npc"]["character"]["race"]["armor"]["anyOf"]["1"] | components["schemas"]["npcSchemas"]["createRandomNpcResponseSchema"]["npc"]["character"]["race"]["skills"]["anyOf"]["2"];
                  })[];
              };
              enableGenerator?: boolean;
              ageAdult?: string;
              ageMax?: string;
              heightMin?: number;
              heightMax?: number;
              nameType?: (string)[];
              addSurname?: number;
              image?: {
                imgdir: string;
                lastedited: number;
              };
              searchTags?: (string)[];
              environments?: (string)[];
              backgroundImage?: string;
              background?: {
                [key: string]: unknown;
              };
            };
            racevariant?: {
              name: string;
              /** @enum {string} */
              pronouns?: "male" | "female" | "neutral" | "thing";
              alignment?: [number,number,number];
              armor?: components["schemas"]["npcSchemas"]["createRandomNpcResponseSchema"]["npc"]["character"]["race"]["armor"]["anyOf"]["0"] | components["schemas"]["npcSchemas"]["createRandomNpcResponseSchema"]["npc"]["character"]["race"]["armor"]["anyOf"]["1"];
              subtypes?: (components["schemas"]["npcSchemas"]["createRandomNpcResponseSchema"]["npc"]["character"]["race"]["subtypes"]["items"])[];
              speeds?: components["schemas"]["npcSchemas"]["createRandomNpcResponseSchema"]["npc"]["character"]["race"]["speeds"];
              savingThrows?: (components["schemas"]["npcSchemas"]["createRandomNpcResponseSchema"]["npc"]["character"]["race"]["subtypes"]["items"])[];
              skills?: (components["schemas"]["npcSchemas"]["createRandomNpcResponseSchema"]["npc"]["character"]["race"]["subtypes"]["items"])[] | components["schemas"]["npcSchemas"]["createRandomNpcResponseSchema"]["npc"]["character"]["race"]["armor"]["anyOf"]["1"] | components["schemas"]["npcSchemas"]["createRandomNpcResponseSchema"]["npc"]["character"]["race"]["skills"]["anyOf"]["2"];
              resistances?: (components["schemas"]["npcSchemas"]["createRandomNpcResponseSchema"]["npc"]["character"]["race"]["subtypes"]["items"])[];
              immunities?: (components["schemas"]["npcSchemas"]["createRandomNpcResponseSchema"]["npc"]["character"]["race"]["subtypes"]["items"])[];
              vulnerabilities?: (components["schemas"]["npcSchemas"]["createRandomNpcResponseSchema"]["npc"]["character"]["race"]["subtypes"]["items"])[];
              conditionImmunities?: (components["schemas"]["npcSchemas"]["createRandomNpcResponseSchema"]["npc"]["character"]["race"]["subtypes"]["items"])[];
              senses?: components["schemas"]["npcSchemas"]["createRandomNpcResponseSchema"]["npc"]["character"]["race"]["senses"];
              isBlind?: boolean;
              canSpeak?: boolean;
              telepathy?: string;
              languages?: (components["schemas"]["npcSchemas"]["createRandomNpcResponseSchema"]["npc"]["character"]["race"]["subtypes"]["items"])[] | components["schemas"]["npcSchemas"]["createRandomNpcResponseSchema"]["npc"]["character"]["race"]["armor"]["anyOf"]["1"] | components["schemas"]["npcSchemas"]["createRandomNpcResponseSchema"]["npc"]["character"]["race"]["skills"]["anyOf"]["2"];
              actions?: (components["schemas"]["npcSchemas"]["createRandomNpcResponseSchema"]["npc"]["character"]["race"]["actions"]["items"])[];
              spells?: components["schemas"]["npcSchemas"]["createRandomNpcResponseSchema"]["npc"]["character"]["race"]["spells"];
              enableGenerator?: boolean;
              image?: components["schemas"]["npcSchemas"]["createRandomNpcResponseSchema"]["npc"]["character"]["race"]["image"];
              searchTags?: (string)[];
              environments?: (string)[];
              backgroundImage?: string;
              background?: {
                [key: string]: unknown;
              };
            };
            class?: {
              name: string;
              armor?: components["schemas"]["npcSchemas"]["createRandomNpcResponseSchema"]["npc"]["character"]["race"]["armor"]["anyOf"]["0"] | components["schemas"]["npcSchemas"]["createRandomNpcResponseSchema"]["npc"]["character"]["race"]["armor"]["anyOf"]["1"];
              subtypes?: (components["schemas"]["npcSchemas"]["createRandomNpcResponseSchema"]["npc"]["character"]["race"]["subtypes"]["items"])[];
              speeds?: components["schemas"]["npcSchemas"]["createRandomNpcResponseSchema"]["npc"]["character"]["race"]["speeds"];
              savingThrows?: (components["schemas"]["npcSchemas"]["createRandomNpcResponseSchema"]["npc"]["character"]["race"]["subtypes"]["items"])[];
              skills?: (components["schemas"]["npcSchemas"]["createRandomNpcResponseSchema"]["npc"]["character"]["race"]["subtypes"]["items"])[] | components["schemas"]["npcSchemas"]["createRandomNpcResponseSchema"]["npc"]["character"]["race"]["armor"]["anyOf"]["1"] | components["schemas"]["npcSchemas"]["createRandomNpcResponseSchema"]["npc"]["character"]["race"]["skills"]["anyOf"]["2"];
              resistances?: (components["schemas"]["npcSchemas"]["createRandomNpcResponseSchema"]["npc"]["character"]["race"]["subtypes"]["items"])[];
              immunities?: (components["schemas"]["npcSchemas"]["createRandomNpcResponseSchema"]["npc"]["character"]["race"]["subtypes"]["items"])[];
              vulnerabilities?: (components["schemas"]["npcSchemas"]["createRandomNpcResponseSchema"]["npc"]["character"]["race"]["subtypes"]["items"])[];
              conditionImmunities?: (components["schemas"]["npcSchemas"]["createRandomNpcResponseSchema"]["npc"]["character"]["race"]["subtypes"]["items"])[];
              senses?: components["schemas"]["npcSchemas"]["createRandomNpcResponseSchema"]["npc"]["character"]["race"]["senses"];
              isBlind?: boolean;
              canSpeak?: boolean;
              telepathy?: string;
              languages?: (components["schemas"]["npcSchemas"]["createRandomNpcResponseSchema"]["npc"]["character"]["race"]["subtypes"]["items"])[] | components["schemas"]["npcSchemas"]["createRandomNpcResponseSchema"]["npc"]["character"]["race"]["armor"]["anyOf"]["1"] | components["schemas"]["npcSchemas"]["createRandomNpcResponseSchema"]["npc"]["character"]["race"]["skills"]["anyOf"]["2"];
              actions?: (components["schemas"]["npcSchemas"]["createRandomNpcResponseSchema"]["npc"]["character"]["race"]["actions"]["items"])[];
              bonuses?: components["schemas"]["npcSchemas"]["createRandomNpcResponseSchema"]["npc"]["character"]["race"]["bonuses"];
              spells?: components["schemas"]["npcSchemas"]["createRandomNpcResponseSchema"]["npc"]["character"]["race"]["spells"];
              enableGenerator?: boolean;
              image?: components["schemas"]["npcSchemas"]["createRandomNpcResponseSchema"]["npc"]["character"]["race"]["image"];
              searchTags?: (string)[];
              environments?: (string)[];
              backgroundImage?: string;
              background?: {
                [key: string]: unknown;
              };
            };
            classvariant?: {
              name: string;
              armor?: components["schemas"]["npcSchemas"]["createRandomNpcResponseSchema"]["npc"]["character"]["race"]["armor"]["anyOf"]["0"] | components["schemas"]["npcSchemas"]["createRandomNpcResponseSchema"]["npc"]["character"]["race"]["armor"]["anyOf"]["1"];
              subtypes?: (components["schemas"]["npcSchemas"]["createRandomNpcResponseSchema"]["npc"]["character"]["race"]["subtypes"]["items"])[];
              speeds?: components["schemas"]["npcSchemas"]["createRandomNpcResponseSchema"]["npc"]["character"]["race"]["speeds"];
              savingThrows?: (components["schemas"]["npcSchemas"]["createRandomNpcResponseSchema"]["npc"]["character"]["race"]["subtypes"]["items"])[];
              skills?: (components["schemas"]["npcSchemas"]["createRandomNpcResponseSchema"]["npc"]["character"]["race"]["subtypes"]["items"])[] | components["schemas"]["npcSchemas"]["createRandomNpcResponseSchema"]["npc"]["character"]["race"]["armor"]["anyOf"]["1"] | components["schemas"]["npcSchemas"]["createRandomNpcResponseSchema"]["npc"]["character"]["race"]["skills"]["anyOf"]["2"];
              resistances?: (components["schemas"]["npcSchemas"]["createRandomNpcResponseSchema"]["npc"]["character"]["race"]["subtypes"]["items"])[];
              immunities?: (components["schemas"]["npcSchemas"]["createRandomNpcResponseSchema"]["npc"]["character"]["race"]["subtypes"]["items"])[];
              vulnerabilities?: (components["schemas"]["npcSchemas"]["createRandomNpcResponseSchema"]["npc"]["character"]["race"]["subtypes"]["items"])[];
              conditionImmunities?: (components["schemas"]["npcSchemas"]["createRandomNpcResponseSchema"]["npc"]["character"]["race"]["subtypes"]["items"])[];
              senses?: components["schemas"]["npcSchemas"]["createRandomNpcResponseSchema"]["npc"]["character"]["race"]["senses"];
              isBlind?: boolean;
              canSpeak?: boolean;
              telepathy?: string;
              languages?: (components["schemas"]["npcSchemas"]["createRandomNpcResponseSchema"]["npc"]["character"]["race"]["subtypes"]["items"])[] | components["schemas"]["npcSchemas"]["createRandomNpcResponseSchema"]["npc"]["character"]["race"]["armor"]["anyOf"]["1"] | components["schemas"]["npcSchemas"]["createRandomNpcResponseSchema"]["npc"]["character"]["race"]["skills"]["anyOf"]["2"];
              actions?: (components["schemas"]["npcSchemas"]["createRandomNpcResponseSchema"]["npc"]["character"]["race"]["actions"]["items"])[];
              bonuses?: components["schemas"]["npcSchemas"]["createRandomNpcResponseSchema"]["npc"]["character"]["race"]["bonuses"];
              spells?: components["schemas"]["npcSchemas"]["createRandomNpcResponseSchema"]["npc"]["character"]["race"]["spells"];
              enableGenerator?: boolean;
              image?: components["schemas"]["npcSchemas"]["createRandomNpcResponseSchema"]["npc"]["character"]["race"]["image"];
              searchTags?: (string)[];
              environments?: (string)[];
              backgroundImage?: string;
              background?: {
                [key: string]: unknown;
              };
            };
            profession?: {
              name: string;
              femaleName: string;
              workplace: string;
              armor?: components["schemas"]["npcSchemas"]["createRandomNpcResponseSchema"]["npc"]["character"]["race"]["armor"]["anyOf"]["0"] | components["schemas"]["npcSchemas"]["createRandomNpcResponseSchema"]["npc"]["character"]["race"]["armor"]["anyOf"]["1"];
              alignment?: [number,number,number];
              subtypes?: (components["schemas"]["npcSchemas"]["createRandomNpcResponseSchema"]["npc"]["character"]["race"]["subtypes"]["items"])[];
              speeds?: components["schemas"]["npcSchemas"]["createRandomNpcResponseSchema"]["npc"]["character"]["race"]["speeds"];
              savingThrows?: (components["schemas"]["npcSchemas"]["createRandomNpcResponseSchema"]["npc"]["character"]["race"]["subtypes"]["items"])[];
              skills?: (components["schemas"]["npcSchemas"]["createRandomNpcResponseSchema"]["npc"]["character"]["race"]["subtypes"]["items"])[] | components["schemas"]["npcSchemas"]["createRandomNpcResponseSchema"]["npc"]["character"]["race"]["armor"]["anyOf"]["1"] | components["schemas"]["npcSchemas"]["createRandomNpcResponseSchema"]["npc"]["character"]["race"]["skills"]["anyOf"]["2"];
              resistances?: (components["schemas"]["npcSchemas"]["createRandomNpcResponseSchema"]["npc"]["character"]["race"]["subtypes"]["items"])[];
              immunities?: (components["schemas"]["npcSchemas"]["createRandomNpcResponseSchema"]["npc"]["character"]["race"]["subtypes"]["items"])[];
              vulnerabilities?: (components["schemas"]["npcSchemas"]["createRandomNpcResponseSchema"]["npc"]["character"]["race"]["subtypes"]["items"])[];
              conditionImmunities?: (components["schemas"]["npcSchemas"]["createRandomNpcResponseSchema"]["npc"]["character"]["race"]["subtypes"]["items"])[];
              senses?: components["schemas"]["npcSchemas"]["createRandomNpcResponseSchema"]["npc"]["character"]["race"]["senses"];
              isBlind?: boolean;
              canSpeak?: boolean;
              telepathy?: string;
              languages?: (components["schemas"]["npcSchemas"]["createRandomNpcResponseSchema"]["npc"]["character"]["race"]["subtypes"]["items"])[] | components["schemas"]["npcSchemas"]["createRandomNpcResponseSchema"]["npc"]["character"]["race"]["armor"]["anyOf"]["1"] | components["schemas"]["npcSchemas"]["createRandomNpcResponseSchema"]["npc"]["character"]["race"]["skills"]["anyOf"]["2"];
              actions?: (components["schemas"]["npcSchemas"]["createRandomNpcResponseSchema"]["npc"]["character"]["race"]["actions"]["items"] | components["schemas"]["npcSchemas"]["createRandomNpcResponseSchema"]["npc"]["character"]["race"]["armor"]["anyOf"]["1"])[];
              bonuses?: components["schemas"]["npcSchemas"]["createRandomNpcResponseSchema"]["npc"]["character"]["race"]["bonuses"];
              spells?: components["schemas"]["npcSchemas"]["createRandomNpcResponseSchema"]["npc"]["character"]["race"]["spells"];
              enableGenerator?: boolean;
            };
            template?: {
              name: string;
              /** @enum {string} */
              pronouns?: "male" | "female" | "neutral" | "thing";
              size?: string;
              type?: string;
              isSwarm?: boolean;
              swarmSize?: string;
              subtypes?: (components["schemas"]["npcSchemas"]["createRandomNpcResponseSchema"]["npc"]["character"]["race"]["subtypes"]["items"])[];
              alignment?: [number,number,number];
              armor?: components["schemas"]["npcSchemas"]["createRandomNpcResponseSchema"]["npc"]["character"]["race"]["armor"]["anyOf"]["0"] | components["schemas"]["npcSchemas"]["createRandomNpcResponseSchema"]["npc"]["character"]["race"]["armor"]["anyOf"]["1"];
              HD?: number;
              speeds?: components["schemas"]["npcSchemas"]["createRandomNpcResponseSchema"]["npc"]["character"]["race"]["speeds"];
              abilitiesBase?: {
                STR?: string;
                DEX?: string;
                CON?: string;
                INT?: string;
                WIS?: string;
                CHA?: string;
              };
              savingThrows?: (components["schemas"]["npcSchemas"]["createRandomNpcResponseSchema"]["npc"]["character"]["race"]["subtypes"]["items"])[];
              skills?: (components["schemas"]["npcSchemas"]["createRandomNpcResponseSchema"]["npc"]["character"]["race"]["subtypes"]["items"])[] | components["schemas"]["npcSchemas"]["createRandomNpcResponseSchema"]["npc"]["character"]["race"]["armor"]["anyOf"]["1"] | components["schemas"]["npcSchemas"]["createRandomNpcResponseSchema"]["npc"]["character"]["race"]["skills"]["anyOf"]["2"];
              resistances?: (components["schemas"]["npcSchemas"]["createRandomNpcResponseSchema"]["npc"]["character"]["race"]["subtypes"]["items"])[];
              immunities?: (components["schemas"]["npcSchemas"]["createRandomNpcResponseSchema"]["npc"]["character"]["race"]["subtypes"]["items"])[];
              vulnerabilities?: (components["schemas"]["npcSchemas"]["createRandomNpcResponseSchema"]["npc"]["character"]["race"]["subtypes"]["items"])[];
              conditionImmunities?: (components["schemas"]["npcSchemas"]["createRandomNpcResponseSchema"]["npc"]["character"]["race"]["subtypes"]["items"])[];
              senses?: components["schemas"]["npcSchemas"]["createRandomNpcResponseSchema"]["npc"]["character"]["race"]["senses"];
              isBlind?: boolean;
              canSpeak?: boolean;
              telepathy?: string;
              languages?: (components["schemas"]["npcSchemas"]["createRandomNpcResponseSchema"]["npc"]["character"]["race"]["subtypes"]["items"])[] | components["schemas"]["npcSchemas"]["createRandomNpcResponseSchema"]["npc"]["character"]["race"]["armor"]["anyOf"]["1"] | components["schemas"]["npcSchemas"]["createRandomNpcResponseSchema"]["npc"]["character"]["race"]["skills"]["anyOf"]["2"];
              actions?: (components["schemas"]["npcSchemas"]["createRandomNpcResponseSchema"]["npc"]["character"]["race"]["actions"]["items"])[];
              bonuses?: components["schemas"]["npcSchemas"]["createRandomNpcResponseSchema"]["npc"]["character"]["race"]["bonuses"];
              spellCasting?: components["schemas"]["npcSchemas"]["createRandomNpcResponseSchema"]["npc"]["character"]["race"]["actions"]["items"]["variants"]["items"]["anyOf"]["0"]["ability"];
              spells?: components["schemas"]["npcSchemas"]["createRandomNpcResponseSchema"]["npc"]["character"]["race"]["spells"];
              image?: components["schemas"]["npcSchemas"]["createRandomNpcResponseSchema"]["npc"]["character"]["race"]["image"];
              searchTags?: (string)[];
              environments?: (string)[];
              backgroundImage?: string;
              background?: {
                [key: string]: unknown;
              };
            };
            user?: {
              name: string;
              /** @enum {string} */
              gender?: "male" | "female" | "neutral" | "thing";
              size?: string;
              type?: string;
              isSwarm?: boolean;
              swarmSize?: string;
              subtypes?: (components["schemas"]["npcSchemas"]["createRandomNpcResponseSchema"]["npc"]["character"]["race"]["subtypes"]["items"])[];
              armor?: components["schemas"]["npcSchemas"]["createRandomNpcResponseSchema"]["npc"]["character"]["race"]["armor"]["anyOf"]["0"] | components["schemas"]["npcSchemas"]["createRandomNpcResponseSchema"]["npc"]["character"]["race"]["armor"]["anyOf"]["1"];
              HD?: number;
              speeds?: components["schemas"]["npcSchemas"]["createRandomNpcResponseSchema"]["npc"]["character"]["race"]["speeds"];
              abilitiesBase?: components["schemas"]["npcSchemas"]["createRandomNpcResponseSchema"]["npc"]["character"]["template"]["abilitiesBase"];
              savingThrows?: (components["schemas"]["npcSchemas"]["createRandomNpcResponseSchema"]["npc"]["character"]["race"]["subtypes"]["items"])[];
              skills?: (components["schemas"]["npcSchemas"]["createRandomNpcResponseSchema"]["npc"]["character"]["race"]["subtypes"]["items"])[] | components["schemas"]["npcSchemas"]["createRandomNpcResponseSchema"]["npc"]["character"]["race"]["armor"]["anyOf"]["1"] | components["schemas"]["npcSchemas"]["createRandomNpcResponseSchema"]["npc"]["character"]["race"]["skills"]["anyOf"]["2"];
              resistances?: (components["schemas"]["npcSchemas"]["createRandomNpcResponseSchema"]["npc"]["character"]["race"]["subtypes"]["items"])[];
              immunities?: (components["schemas"]["npcSchemas"]["createRandomNpcResponseSchema"]["npc"]["character"]["race"]["subtypes"]["items"])[];
              vulnerabilities?: (components["schemas"]["npcSchemas"]["createRandomNpcResponseSchema"]["npc"]["character"]["race"]["subtypes"]["items"])[];
              conditionImmunities?: (components["schemas"]["npcSchemas"]["createRandomNpcResponseSchema"]["npc"]["character"]["race"]["subtypes"]["items"])[];
              senses?: components["schemas"]["npcSchemas"]["createRandomNpcResponseSchema"]["npc"]["character"]["race"]["senses"];
              isBlind?: boolean;
              canSpeak?: boolean;
              telepathy?: string;
              languages?: (components["schemas"]["npcSchemas"]["createRandomNpcResponseSchema"]["npc"]["character"]["race"]["subtypes"]["items"])[] | components["schemas"]["npcSchemas"]["createRandomNpcResponseSchema"]["npc"]["character"]["race"]["armor"]["anyOf"]["1"] | components["schemas"]["npcSchemas"]["createRandomNpcResponseSchema"]["npc"]["character"]["race"]["skills"]["anyOf"]["2"];
              actions?: (components["schemas"]["npcSchemas"]["createRandomNpcResponseSchema"]["npc"]["character"]["race"]["actions"]["items"])[];
              bonuses?: components["schemas"]["npcSchemas"]["createRandomNpcResponseSchema"]["npc"]["character"]["race"]["bonuses"];
              spells?: components["schemas"]["npcSchemas"]["createRandomNpcResponseSchema"]["npc"]["character"]["race"]["spells"];
              image?: components["schemas"]["npcSchemas"]["createRandomNpcResponseSchema"]["npc"]["character"]["race"]["image"];
              searchTags?: (string)[];
              environments?: (string)[];
              backgroundImage?: string;
              background?: {
                [key: string]: unknown;
              };
              smallbackground?: string;
              trait?: string;
            };
            abilitiesBase?: components["schemas"]["npcSchemas"]["createRandomNpcResponseSchema"]["npc"]["character"]["template"]["abilitiesBase"];
            alignment?: [number,number,number];
            /** @enum {string} */
            alignmentEthical?: "Lawful" | "Neutral" | "Chaotic" | "Any" | "Unaligned";
            /** @enum {string} */
            alignmentMoral?: "Good" | "Neutral" | "Evil" | "Any";
            smallbackground?: string;
            trait?: string;
            feeling?: string;
            CRCalculation?: {
              x1: string;
              x2: string;
              y1: string;
              y2: string;
              /** @enum {string} */
              name: "twopoints";
            } | {
              /** @enum {string} */
              name: "npcstandard";
            } | {
              /** @enum {string} */
              name: "estimated";
            };
          };
          statistics: {
            alignment: (string)[];
          };
        };
      };
      createFourRandomNpcsResponseSchema: {
        npcs: (components["schemas"]["npcSchemas"]["createRandomNpcResponseSchema"]["npc"])[];
      };
    };
    professionSchemas: {
      createProfessionSchema: {
        object: {
          name: string;
          femaleName: string;
          workplace: string;
          armor?: ({
            AC: string;
            name: string;
            cost?: string;
            /** @enum {string} */
            type?: "light" | "medium" | "heavy";
            maxDex?: string;
            minStr?: string;
            weight?: string;
            /** @enum {string} */
            stealthDis?: "0" | "1";
          }) | ({
            choice: {
              /** @enum {string} */
              type: "random";
              number?: number;
              /** @enum {string} */
              resultType: "object" | "nameId";
              /** @enum {string} */
              source: "objects" | "languages" | "skills";
              objectType?: number;
              filters?: ({
                  keyName: string;
                  keyValues: (string)[];
                })[];
              chosenAlready?: ({
                  id?: number;
                  value: string;
                  levelMin?: string;
                })[];
            };
          });
          alignment?: [number,number,number];
          subtypes?: (components["schemas"]["professionSchemas"]["createProfessionSchema"]["object"]["armor"]["anyOf"]["1"]["choice"]["chosenAlready"]["items"])[];
          speeds?: {
            base?: string;
            burrow?: string;
            climb?: string;
            fly?: string;
            hover?: string;
            swim?: string;
          };
          savingThrows?: (components["schemas"]["professionSchemas"]["createProfessionSchema"]["object"]["armor"]["anyOf"]["1"]["choice"]["chosenAlready"]["items"])[];
          skills?: (components["schemas"]["professionSchemas"]["createProfessionSchema"]["object"]["armor"]["anyOf"]["1"]["choice"]["chosenAlready"]["items"])[] | components["schemas"]["professionSchemas"]["createProfessionSchema"]["object"]["armor"]["anyOf"]["1"] | {
            choice: {
              /** @enum {string} */
              type: "list";
              number: number;
              list: (components["schemas"]["professionSchemas"]["createProfessionSchema"]["object"]["armor"]["anyOf"]["1"]["choice"]["chosenAlready"]["items"])[];
              isRepeatable?: boolean;
            };
          };
          resistances?: (components["schemas"]["professionSchemas"]["createProfessionSchema"]["object"]["armor"]["anyOf"]["1"]["choice"]["chosenAlready"]["items"])[];
          immunities?: (components["schemas"]["professionSchemas"]["createProfessionSchema"]["object"]["armor"]["anyOf"]["1"]["choice"]["chosenAlready"]["items"])[];
          vulnerabilities?: (components["schemas"]["professionSchemas"]["createProfessionSchema"]["object"]["armor"]["anyOf"]["1"]["choice"]["chosenAlready"]["items"])[];
          conditionImmunities?: (components["schemas"]["professionSchemas"]["createProfessionSchema"]["object"]["armor"]["anyOf"]["1"]["choice"]["chosenAlready"]["items"])[];
          senses?: {
            blindsight?: string;
            darkvision?: string;
            tremorsense?: string;
            truesight?: string;
          };
          isBlind?: boolean;
          canSpeak?: boolean;
          telepathy?: string;
          languages?: (components["schemas"]["professionSchemas"]["createProfessionSchema"]["object"]["armor"]["anyOf"]["1"]["choice"]["chosenAlready"]["items"])[] | components["schemas"]["professionSchemas"]["createProfessionSchema"]["object"]["armor"]["anyOf"]["1"] | components["schemas"]["professionSchemas"]["createProfessionSchema"]["object"]["skills"]["anyOf"]["2"];
          actions?: (({
              tag: string;
              /** @enum {string} */
              actionType?: "trait" | "legendary" | "action" | "reaction" | "bonus" | "attack" | "multiattack" | "mythic" | "lair";
              subType?: string;
              source?: string;
              tags?: (string)[];
              priority?: number;
              variants: (({
                  name: string;
                  description: string;
                  /** @enum {string} */
                  type: "trait" | "legendary" | "action" | "reaction" | "bonus" | "attack" | "multiattack" | "mythic" | "lair";
                  levelMin?: number;
                  levelMax?: number;
                  /** @enum {string} */
                  ability?: "STR" | "DEX" | "CON" | "INT" | "WIS" | "CHA";
                  charges?: string;
                  recharge?: string;
                  cost?: string;
                  values?: ({
                      name: string;
                      type?: string;
                      expression: string;
                    } | {
                      name: string;
                      type?: string;
                      expression?: string;
                      dice: {
                        die: string;
                        diceNumber: string;
                        diceIncrement: string;
                        levelMin: string;
                        levelMax: string;
                        levelInterval: string;
                      };
                    } | {
                      name: string;
                      type?: string;
                      incrProgression: {
                        levelInterval: string;
                        levelIncrement: string;
                        levelMin: string;
                        base: string;
                        increment: string;
                      };
                    })[];
                  attacks?: ({
                      name: string;
                      replaceName?: boolean;
                      attributes: {
                        reach?: string;
                        targets?: string;
                        name?: string;
                        cost?: string;
                        weight?: string;
                        damageType?: string;
                        special?: string;
                        die?: string;
                        diceNumber?: string;
                        dieV?: string;
                        diceNumberV?: string;
                        range?: string;
                        rangeMax?: string;
                        properties: (string)[];
                      } | components["schemas"]["professionSchemas"]["createProfessionSchema"]["object"]["armor"]["anyOf"]["1"];
                      enchantment?: {
                        type: string;
                        dice?: components["schemas"]["professionSchemas"]["createProfessionSchema"]["object"]["actions"]["items"]["anyOf"]["0"]["variants"]["items"]["anyOf"]["0"]["values"]["items"]["anyOf"]["1"]["dice"];
                        expression?: string;
                      };
                    })[];
                }) | components["schemas"]["professionSchemas"]["createProfessionSchema"]["object"]["armor"]["anyOf"]["1"] | components["schemas"]["professionSchemas"]["createProfessionSchema"]["object"]["skills"]["anyOf"]["2"])[];
            }) | components["schemas"]["professionSchemas"]["createProfessionSchema"]["object"]["armor"]["anyOf"]["1"])[];
          bonuses?: {
            HPBonus?: {
              name?: string;
              value: string;
            };
            ACBonus?: components["schemas"]["professionSchemas"]["createProfessionSchema"]["object"]["bonuses"]["HPBonus"];
            sizeBonus?: components["schemas"]["professionSchemas"]["createProfessionSchema"]["object"]["bonuses"]["HPBonus"];
            speedBaseBonus?: components["schemas"]["professionSchemas"]["createProfessionSchema"]["object"]["bonuses"]["HPBonus"];
            speedBurrowBonus?: components["schemas"]["professionSchemas"]["createProfessionSchema"]["object"]["bonuses"]["HPBonus"];
            speedClimbBonus?: components["schemas"]["professionSchemas"]["createProfessionSchema"]["object"]["bonuses"]["HPBonus"];
            speedFlyBonus?: components["schemas"]["professionSchemas"]["createProfessionSchema"]["object"]["bonuses"]["HPBonus"];
            speedHoverBonus?: components["schemas"]["professionSchemas"]["createProfessionSchema"]["object"]["bonuses"]["HPBonus"];
            speedSwimBonus?: components["schemas"]["professionSchemas"]["createProfessionSchema"]["object"]["bonuses"]["HPBonus"];
            STRBonus?: components["schemas"]["professionSchemas"]["createProfessionSchema"]["object"]["bonuses"]["HPBonus"];
            DEXBonus?: components["schemas"]["professionSchemas"]["createProfessionSchema"]["object"]["bonuses"]["HPBonus"];
            CONBonus?: components["schemas"]["professionSchemas"]["createProfessionSchema"]["object"]["bonuses"]["HPBonus"];
            INTBonus?: components["schemas"]["professionSchemas"]["createProfessionSchema"]["object"]["bonuses"]["HPBonus"];
            WISBonus?: components["schemas"]["professionSchemas"]["createProfessionSchema"]["object"]["bonuses"]["HPBonus"];
            CHABonus?: components["schemas"]["professionSchemas"]["createProfessionSchema"]["object"]["bonuses"]["HPBonus"];
            STRSaveBonus?: components["schemas"]["professionSchemas"]["createProfessionSchema"]["object"]["bonuses"]["HPBonus"];
            DEXSaveBonus?: components["schemas"]["professionSchemas"]["createProfessionSchema"]["object"]["bonuses"]["HPBonus"];
            CONSaveBonus?: components["schemas"]["professionSchemas"]["createProfessionSchema"]["object"]["bonuses"]["HPBonus"];
            INTSaveBonus?: components["schemas"]["professionSchemas"]["createProfessionSchema"]["object"]["bonuses"]["HPBonus"];
            WISSaveBonus?: components["schemas"]["professionSchemas"]["createProfessionSchema"]["object"]["bonuses"]["HPBonus"];
            CHASaveBonus?: components["schemas"]["professionSchemas"]["createProfessionSchema"]["object"]["bonuses"]["HPBonus"];
            AthleticsBonus?: components["schemas"]["professionSchemas"]["createProfessionSchema"]["object"]["bonuses"]["HPBonus"];
            AcrobaticsBonus?: components["schemas"]["professionSchemas"]["createProfessionSchema"]["object"]["bonuses"]["HPBonus"];
            SleightOfHandBonus?: components["schemas"]["professionSchemas"]["createProfessionSchema"]["object"]["bonuses"]["HPBonus"];
            StealthBonus?: components["schemas"]["professionSchemas"]["createProfessionSchema"]["object"]["bonuses"]["HPBonus"];
            ArcanaBonus?: components["schemas"]["professionSchemas"]["createProfessionSchema"]["object"]["bonuses"]["HPBonus"];
            HistoryBonus?: components["schemas"]["professionSchemas"]["createProfessionSchema"]["object"]["bonuses"]["HPBonus"];
            InvestigationBonus?: components["schemas"]["professionSchemas"]["createProfessionSchema"]["object"]["bonuses"]["HPBonus"];
            NatureBonus?: components["schemas"]["professionSchemas"]["createProfessionSchema"]["object"]["bonuses"]["HPBonus"];
            ReligionBonus?: components["schemas"]["professionSchemas"]["createProfessionSchema"]["object"]["bonuses"]["HPBonus"];
            AnimalHandlingBonus?: components["schemas"]["professionSchemas"]["createProfessionSchema"]["object"]["bonuses"]["HPBonus"];
            InsightBonus?: components["schemas"]["professionSchemas"]["createProfessionSchema"]["object"]["bonuses"]["HPBonus"];
            MedicineBonus?: components["schemas"]["professionSchemas"]["createProfessionSchema"]["object"]["bonuses"]["HPBonus"];
            PerceptionBonus?: components["schemas"]["professionSchemas"]["createProfessionSchema"]["object"]["bonuses"]["HPBonus"];
            SurvivalBonus?: components["schemas"]["professionSchemas"]["createProfessionSchema"]["object"]["bonuses"]["HPBonus"];
            DeceptionBonus?: components["schemas"]["professionSchemas"]["createProfessionSchema"]["object"]["bonuses"]["HPBonus"];
            IntimidationBonus?: components["schemas"]["professionSchemas"]["createProfessionSchema"]["object"]["bonuses"]["HPBonus"];
            PerformanceBonus?: components["schemas"]["professionSchemas"]["createProfessionSchema"]["object"]["bonuses"]["HPBonus"];
            PersuasionBonus?: components["schemas"]["professionSchemas"]["createProfessionSchema"]["object"]["bonuses"]["HPBonus"];
            blindsightBonus?: components["schemas"]["professionSchemas"]["createProfessionSchema"]["object"]["bonuses"]["HPBonus"];
            darkvisionBonus?: components["schemas"]["professionSchemas"]["createProfessionSchema"]["object"]["bonuses"]["HPBonus"];
            tremorsenseBonus?: components["schemas"]["professionSchemas"]["createProfessionSchema"]["object"]["bonuses"]["HPBonus"];
            truesightBonus?: components["schemas"]["professionSchemas"]["createProfessionSchema"]["object"]["bonuses"]["HPBonus"];
            rangedAttackBonus?: components["schemas"]["professionSchemas"]["createProfessionSchema"]["object"]["bonuses"]["HPBonus"];
            rangedDamageBonus?: components["schemas"]["professionSchemas"]["createProfessionSchema"]["object"]["bonuses"]["HPBonus"];
            meleeAttackBonus?: components["schemas"]["professionSchemas"]["createProfessionSchema"]["object"]["bonuses"]["HPBonus"];
            meleeDamageBonus?: components["schemas"]["professionSchemas"]["createProfessionSchema"]["object"]["bonuses"]["HPBonus"];
            spellAttackBonus?: components["schemas"]["professionSchemas"]["createProfessionSchema"]["object"]["bonuses"]["HPBonus"];
            spellDamageBonus?: components["schemas"]["professionSchemas"]["createProfessionSchema"]["object"]["bonuses"]["HPBonus"];
            weaponAttackBonus?: components["schemas"]["professionSchemas"]["createProfessionSchema"]["object"]["bonuses"]["HPBonus"];
            weaponDamageBonus?: components["schemas"]["professionSchemas"]["createProfessionSchema"]["object"]["bonuses"]["HPBonus"];
          };
          spells?: {
            hasSlots?: boolean;
            ability?: components["schemas"]["professionSchemas"]["createProfessionSchema"]["object"]["actions"]["items"]["anyOf"]["0"]["variants"]["items"]["anyOf"]["0"]["ability"];
            groups?: ({
                tag: string;
                levelMin?: string;
                timesDay?: string;
                timesDayMax?: string;
                spells: (components["schemas"]["professionSchemas"]["createProfessionSchema"]["object"]["armor"]["anyOf"]["1"]["choice"]["chosenAlready"]["items"])[] | components["schemas"]["professionSchemas"]["createProfessionSchema"]["object"]["armor"]["anyOf"]["1"] | components["schemas"]["professionSchemas"]["createProfessionSchema"]["object"]["skills"]["anyOf"]["2"];
              })[];
          };
          enableGenerator?: boolean;
        };
        /** @enum {string} */
        age: "medieval" | "fantasy" | "renaissance" | "modern" | "future" | "space" | "other";
        description: string;
        game: number;
      };
      getProfessionListResponseSchema: {
        list: ({
            id: number;
            userid: number;
            name: string;
          })[];
      };
      getProfessionResponseSchema: {
        object: components["schemas"]["professionSchemas"]["createProfessionSchema"]["object"];
        id: components["schemas"]["professionSchemas"]["getProfessionListResponseSchema"]["list"]["items"]["id"];
      };
    };
    raceSchemas: {
      createRaceSchema: {
        game: number;
        object: {
          name: string;
          /** @enum {string} */
          pronouns?: "male" | "female" | "neutral" | "thing";
          size?: string;
          type?: string;
          isSwarm?: boolean;
          swarmSize?: string;
          subtypes?: ({
              id?: number;
              value: string;
              levelMin?: string;
            })[];
          alignment?: [number,number,number];
          armor?: ({
            AC: string;
            name: string;
            cost?: string;
            /** @enum {string} */
            type?: "light" | "medium" | "heavy";
            maxDex?: string;
            minStr?: string;
            weight?: string;
            /** @enum {string} */
            stealthDis?: "0" | "1";
          }) | ({
            choice: {
              /** @enum {string} */
              type: "random";
              number?: number;
              /** @enum {string} */
              resultType: "object" | "nameId";
              /** @enum {string} */
              source: "objects" | "languages" | "skills";
              objectType?: number;
              filters?: ({
                  keyName: string;
                  keyValues: (string)[];
                })[];
              chosenAlready?: (components["schemas"]["raceSchemas"]["createRaceSchema"]["object"]["subtypes"]["items"])[];
            };
          });
          HD?: number;
          abilitiesLimit?: string;
          speeds?: {
            base?: string;
            burrow?: string;
            climb?: string;
            fly?: string;
            hover?: string;
            swim?: string;
          };
          savingThrows?: (components["schemas"]["raceSchemas"]["createRaceSchema"]["object"]["subtypes"]["items"])[];
          skills?: (components["schemas"]["raceSchemas"]["createRaceSchema"]["object"]["subtypes"]["items"])[] | components["schemas"]["raceSchemas"]["createRaceSchema"]["object"]["armor"]["anyOf"]["1"] | {
            choice: {
              /** @enum {string} */
              type: "list";
              number: number;
              list: (components["schemas"]["raceSchemas"]["createRaceSchema"]["object"]["subtypes"]["items"])[];
              isRepeatable?: boolean;
            };
          };
          resistances?: (components["schemas"]["raceSchemas"]["createRaceSchema"]["object"]["subtypes"]["items"])[];
          immunities?: (components["schemas"]["raceSchemas"]["createRaceSchema"]["object"]["subtypes"]["items"])[];
          vulnerabilities?: (components["schemas"]["raceSchemas"]["createRaceSchema"]["object"]["subtypes"]["items"])[];
          conditionImmunities?: (components["schemas"]["raceSchemas"]["createRaceSchema"]["object"]["subtypes"]["items"])[];
          senses?: {
            blindsight?: string;
            darkvision?: string;
            tremorsense?: string;
            truesight?: string;
          };
          isBlind?: boolean;
          canSpeak?: boolean;
          telepathy?: string;
          languages?: (components["schemas"]["raceSchemas"]["createRaceSchema"]["object"]["subtypes"]["items"])[] | components["schemas"]["raceSchemas"]["createRaceSchema"]["object"]["armor"]["anyOf"]["1"] | components["schemas"]["raceSchemas"]["createRaceSchema"]["object"]["skills"]["anyOf"]["2"];
          actions?: ({
              tag: string;
              /** @enum {string} */
              actionType?: "trait" | "legendary" | "action" | "reaction" | "bonus" | "attack" | "multiattack" | "mythic" | "lair";
              subType?: string;
              source?: string;
              tags?: (string)[];
              priority?: number;
              variants: (({
                  name: string;
                  description: string;
                  /** @enum {string} */
                  type: "trait" | "legendary" | "action" | "reaction" | "bonus" | "attack" | "multiattack" | "mythic" | "lair";
                  levelMin?: number;
                  levelMax?: number;
                  /** @enum {string} */
                  ability?: "STR" | "DEX" | "CON" | "INT" | "WIS" | "CHA";
                  charges?: string;
                  recharge?: string;
                  cost?: string;
                  values?: ({
                      name: string;
                      type?: string;
                      expression: string;
                    } | {
                      name: string;
                      type?: string;
                      expression?: string;
                      dice: {
                        die: string;
                        diceNumber: string;
                        diceIncrement: string;
                        levelMin: string;
                        levelMax: string;
                        levelInterval: string;
                      };
                    } | {
                      name: string;
                      type?: string;
                      incrProgression: {
                        levelInterval: string;
                        levelIncrement: string;
                        levelMin: string;
                        base: string;
                        increment: string;
                      };
                    })[];
                  attacks?: ({
                      name: string;
                      replaceName?: boolean;
                      attributes: {
                        reach?: string;
                        targets?: string;
                        name?: string;
                        cost?: string;
                        weight?: string;
                        damageType?: string;
                        special?: string;
                        die?: string;
                        diceNumber?: string;
                        dieV?: string;
                        diceNumberV?: string;
                        range?: string;
                        rangeMax?: string;
                        properties: (string)[];
                      } | components["schemas"]["raceSchemas"]["createRaceSchema"]["object"]["armor"]["anyOf"]["1"];
                      enchantment?: {
                        type: string;
                        dice?: components["schemas"]["raceSchemas"]["createRaceSchema"]["object"]["actions"]["items"]["variants"]["items"]["anyOf"]["0"]["values"]["items"]["anyOf"]["1"]["dice"];
                        expression?: string;
                      };
                    })[];
                }) | components["schemas"]["raceSchemas"]["createRaceSchema"]["object"]["armor"]["anyOf"]["1"] | components["schemas"]["raceSchemas"]["createRaceSchema"]["object"]["skills"]["anyOf"]["2"])[];
            })[];
          bonuses?: {
            HPBonus?: {
              name?: string;
              value: string;
            };
            ACBonus?: components["schemas"]["raceSchemas"]["createRaceSchema"]["object"]["bonuses"]["HPBonus"];
            sizeBonus?: components["schemas"]["raceSchemas"]["createRaceSchema"]["object"]["bonuses"]["HPBonus"];
            speedBaseBonus?: components["schemas"]["raceSchemas"]["createRaceSchema"]["object"]["bonuses"]["HPBonus"];
            speedBurrowBonus?: components["schemas"]["raceSchemas"]["createRaceSchema"]["object"]["bonuses"]["HPBonus"];
            speedClimbBonus?: components["schemas"]["raceSchemas"]["createRaceSchema"]["object"]["bonuses"]["HPBonus"];
            speedFlyBonus?: components["schemas"]["raceSchemas"]["createRaceSchema"]["object"]["bonuses"]["HPBonus"];
            speedHoverBonus?: components["schemas"]["raceSchemas"]["createRaceSchema"]["object"]["bonuses"]["HPBonus"];
            speedSwimBonus?: components["schemas"]["raceSchemas"]["createRaceSchema"]["object"]["bonuses"]["HPBonus"];
            STRBonus?: components["schemas"]["raceSchemas"]["createRaceSchema"]["object"]["bonuses"]["HPBonus"];
            DEXBonus?: components["schemas"]["raceSchemas"]["createRaceSchema"]["object"]["bonuses"]["HPBonus"];
            CONBonus?: components["schemas"]["raceSchemas"]["createRaceSchema"]["object"]["bonuses"]["HPBonus"];
            INTBonus?: components["schemas"]["raceSchemas"]["createRaceSchema"]["object"]["bonuses"]["HPBonus"];
            WISBonus?: components["schemas"]["raceSchemas"]["createRaceSchema"]["object"]["bonuses"]["HPBonus"];
            CHABonus?: components["schemas"]["raceSchemas"]["createRaceSchema"]["object"]["bonuses"]["HPBonus"];
            STRSaveBonus?: components["schemas"]["raceSchemas"]["createRaceSchema"]["object"]["bonuses"]["HPBonus"];
            DEXSaveBonus?: components["schemas"]["raceSchemas"]["createRaceSchema"]["object"]["bonuses"]["HPBonus"];
            CONSaveBonus?: components["schemas"]["raceSchemas"]["createRaceSchema"]["object"]["bonuses"]["HPBonus"];
            INTSaveBonus?: components["schemas"]["raceSchemas"]["createRaceSchema"]["object"]["bonuses"]["HPBonus"];
            WISSaveBonus?: components["schemas"]["raceSchemas"]["createRaceSchema"]["object"]["bonuses"]["HPBonus"];
            CHASaveBonus?: components["schemas"]["raceSchemas"]["createRaceSchema"]["object"]["bonuses"]["HPBonus"];
            AthleticsBonus?: components["schemas"]["raceSchemas"]["createRaceSchema"]["object"]["bonuses"]["HPBonus"];
            AcrobaticsBonus?: components["schemas"]["raceSchemas"]["createRaceSchema"]["object"]["bonuses"]["HPBonus"];
            SleightOfHandBonus?: components["schemas"]["raceSchemas"]["createRaceSchema"]["object"]["bonuses"]["HPBonus"];
            StealthBonus?: components["schemas"]["raceSchemas"]["createRaceSchema"]["object"]["bonuses"]["HPBonus"];
            ArcanaBonus?: components["schemas"]["raceSchemas"]["createRaceSchema"]["object"]["bonuses"]["HPBonus"];
            HistoryBonus?: components["schemas"]["raceSchemas"]["createRaceSchema"]["object"]["bonuses"]["HPBonus"];
            InvestigationBonus?: components["schemas"]["raceSchemas"]["createRaceSchema"]["object"]["bonuses"]["HPBonus"];
            NatureBonus?: components["schemas"]["raceSchemas"]["createRaceSchema"]["object"]["bonuses"]["HPBonus"];
            ReligionBonus?: components["schemas"]["raceSchemas"]["createRaceSchema"]["object"]["bonuses"]["HPBonus"];
            AnimalHandlingBonus?: components["schemas"]["raceSchemas"]["createRaceSchema"]["object"]["bonuses"]["HPBonus"];
            InsightBonus?: components["schemas"]["raceSchemas"]["createRaceSchema"]["object"]["bonuses"]["HPBonus"];
            MedicineBonus?: components["schemas"]["raceSchemas"]["createRaceSchema"]["object"]["bonuses"]["HPBonus"];
            PerceptionBonus?: components["schemas"]["raceSchemas"]["createRaceSchema"]["object"]["bonuses"]["HPBonus"];
            SurvivalBonus?: components["schemas"]["raceSchemas"]["createRaceSchema"]["object"]["bonuses"]["HPBonus"];
            DeceptionBonus?: components["schemas"]["raceSchemas"]["createRaceSchema"]["object"]["bonuses"]["HPBonus"];
            IntimidationBonus?: components["schemas"]["raceSchemas"]["createRaceSchema"]["object"]["bonuses"]["HPBonus"];
            PerformanceBonus?: components["schemas"]["raceSchemas"]["createRaceSchema"]["object"]["bonuses"]["HPBonus"];
            PersuasionBonus?: components["schemas"]["raceSchemas"]["createRaceSchema"]["object"]["bonuses"]["HPBonus"];
            blindsightBonus?: components["schemas"]["raceSchemas"]["createRaceSchema"]["object"]["bonuses"]["HPBonus"];
            darkvisionBonus?: components["schemas"]["raceSchemas"]["createRaceSchema"]["object"]["bonuses"]["HPBonus"];
            tremorsenseBonus?: components["schemas"]["raceSchemas"]["createRaceSchema"]["object"]["bonuses"]["HPBonus"];
            truesightBonus?: components["schemas"]["raceSchemas"]["createRaceSchema"]["object"]["bonuses"]["HPBonus"];
            rangedAttackBonus?: components["schemas"]["raceSchemas"]["createRaceSchema"]["object"]["bonuses"]["HPBonus"];
            rangedDamageBonus?: components["schemas"]["raceSchemas"]["createRaceSchema"]["object"]["bonuses"]["HPBonus"];
            meleeAttackBonus?: components["schemas"]["raceSchemas"]["createRaceSchema"]["object"]["bonuses"]["HPBonus"];
            meleeDamageBonus?: components["schemas"]["raceSchemas"]["createRaceSchema"]["object"]["bonuses"]["HPBonus"];
            spellAttackBonus?: components["schemas"]["raceSchemas"]["createRaceSchema"]["object"]["bonuses"]["HPBonus"];
            spellDamageBonus?: components["schemas"]["raceSchemas"]["createRaceSchema"]["object"]["bonuses"]["HPBonus"];
            weaponAttackBonus?: components["schemas"]["raceSchemas"]["createRaceSchema"]["object"]["bonuses"]["HPBonus"];
            weaponDamageBonus?: components["schemas"]["raceSchemas"]["createRaceSchema"]["object"]["bonuses"]["HPBonus"];
          };
          spells?: {
            hasSlots?: boolean;
            ability?: components["schemas"]["raceSchemas"]["createRaceSchema"]["object"]["actions"]["items"]["variants"]["items"]["anyOf"]["0"]["ability"];
            groups?: ({
                tag: string;
                levelMin?: string;
                timesDay?: string;
                timesDayMax?: string;
                spells: (components["schemas"]["raceSchemas"]["createRaceSchema"]["object"]["subtypes"]["items"])[] | components["schemas"]["raceSchemas"]["createRaceSchema"]["object"]["armor"]["anyOf"]["1"] | components["schemas"]["raceSchemas"]["createRaceSchema"]["object"]["skills"]["anyOf"]["2"];
              })[];
          };
          enableGenerator?: boolean;
          ageAdult?: string;
          ageMax?: string;
          heightMin?: number;
          heightMax?: number;
          nameType?: (string)[];
          addSurname?: number;
          image?: {
            imgdir: string;
            lastedited: number;
          };
          searchTags?: (string)[];
          environments?: (string)[];
          backgroundImage?: string;
          background?: {
            [key: string]: unknown;
          };
        };
      };
      updateRaceSchema: {
        object: components["schemas"]["raceSchemas"]["createRaceSchema"]["object"];
        game: components["schemas"]["raceSchemas"]["createRaceSchema"]["game"];
      };
      getRaceWithVariantsListResponseSchema: {
        list: ({
            id: number;
            userid: number;
            name: string;
            other_objects: ({
                id: components["schemas"]["raceSchemas"]["getRaceWithVariantsListResponseSchema"]["list"]["items"]["id"];
                name: components["schemas"]["raceSchemas"]["getRaceWithVariantsListResponseSchema"]["list"]["items"]["name"];
                userid: components["schemas"]["raceSchemas"]["getRaceWithVariantsListResponseSchema"]["list"]["items"]["userid"];
              })[];
          })[];
      };
      getRaceListResponseSchema: {
        list: ({
            id: components["schemas"]["raceSchemas"]["getRaceWithVariantsListResponseSchema"]["list"]["items"]["id"];
            userid: components["schemas"]["raceSchemas"]["getRaceWithVariantsListResponseSchema"]["list"]["items"]["userid"];
            name: components["schemas"]["raceSchemas"]["getRaceWithVariantsListResponseSchema"]["list"]["items"]["name"];
          })[];
      };
      getRaceResponseSchema: {
        object: components["schemas"]["raceSchemas"]["createRaceSchema"]["object"];
        id: components["schemas"]["raceSchemas"]["getRaceWithVariantsListResponseSchema"]["list"]["items"]["id"];
      };
    };
    userSchemas: {
      createUserSchema: {
        /** Format: email */
        email: string;
        username: string;
        password: string;
      };
      createUserResponseSchema: {
        email: components["schemas"]["userSchemas"]["createUserSchema"]["email"];
        username: components["schemas"]["userSchemas"]["createUserSchema"]["username"];
        id: number;
      };
      activateUserSchema: {
        token: string;
      };
      reactivateUserSchema: {
        /** Format: email */
        email: string;
      };
      loginSchema: {
        /** Format: email */
        email: string;
        password: string;
      };
      loginResponseSchema: {
        accessToken: string;
      };
      getUserResponseSchema: {
        id: number;
        email: components["schemas"]["userSchemas"]["createUserSchema"]["email"];
        username: components["schemas"]["userSchemas"]["createUserSchema"]["username"];
        level: number;
        /** Format: date-time */
        created: string;
        /** Format: date-time */
        publishsuspension: string;
        avatar: string;
      };
      updateUserSchema: {
        username: string;
        avatar: string;
      };
      resetPasswordSchema: {
        token: string;
        password: string;
      };
    };
  };
  responses: never;
  parameters: never;
  requestBodies: never;
  headers: never;
  pathItems: never;
}

export type external = Record<string, never>;

export type operations = Record<string, never>;
